security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
            memory_cost: 16384 # Amount in KiB. 16 MiB
            time_cost: 2 # Number of iterations
            threads: 4 # Number of parallel threads
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: my_provider
                username_parameter: "login_form[username]"
                password_parameter: "login_form[password]"
            logout:
                path: logout
                target: index
    role_hierarchy:
        ROLE_ADMIN: [ROLE_TEACHER, ROLE_USER]
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }
#        - { path: ^/subject/new, roles: ROLE_TEACHER }
#        - { path: ^/subject/edit, roles: ROLE_TEACHER }
