public:
    path: /{_locale}
    controller: App\Controller\Index\IndexController::public
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: index/index/public.html.twig
        _locale: '%locale%'
